version: "2.1"

services:
  app:
    build: ./
    image: chulm/http2/app:latest
    environment:
      - JVM_MEMORY=-Xmx4g -Xms4g -XX:MetaspaceSize=200m
    ports:
      - 8080:8080
    hostname: http2-app
    healthcheck:
      test: ["CMD", "curl", "-i", "--http2", "http://http2-app:8080/"]
      interval: 5s
      timeout: 5s
      retries: 15

  nginx:
    build: http2-nginx
    image: chulm/http2/nginx:latest
    ports:
      - 80:80
      - 443:443
    links:
      - app:app
    depends_on:
      app:
        condition: service_healthy