version: "2.1"

services:
  app:
    build: ./
    image: chulm/http2/app:latest
    environment:
      - JVM_MEMORY=-Xmx4g -Xms4g -XX:MetaspaceSize=200m
    hostname: app
    container_name: app
    ports:
      - 8080:80
      - 4433:443
    healthcheck:
      test: ["CMD", "curl", "--insecure", "https://localhost:443/"]
      interval: 30s
      timeout: 5s
      retries: 10
